import type { PortfolioContent } from './types';

export const portfolioContent = {
  profile: {
    name: 'Phani Kumar S',
    role: 'AWS DevOps Engineer',
    eyebrow: 'AWS DevOps Engineer · 5+ years in IT',
    statement:
      'I build secure, high-availability AWS infrastructure and automated release pipelines, so teams can ship to production with confidence.',
    summary:
      'I am an AWS DevOps Engineer at Zazz IT Solutions in Hyderabad, with more than five years in IT and over four years working hands-on with AWS. Since August 2024 I have designed and run cloud infrastructure for a global client: networks, compute, containers, and the path from source control to production.\n\nThe platform is a set of Docker-based microservices on Amazon ECS and EKS. CI/CD runs through CodePipeline, CodeBuild, and CodeDeploy, with Bitbucket and SonarQube in the flow so quality is checked before anything is released. I also own certificates and secrets, CloudWatch monitoring, S3 lifecycle policies, Amplify front-end delivery, and the Nginx and Apache edges in front of the applications.\n\nBeyond the Zazz stack I work with Jenkins, Terraform, Ansible, Kubernetes, Maven, Nexus, Splunk, and Datadog, across Linux and Windows. I am comfortable troubleshooting production and non-production issues, and coordinating with engineering teams and stakeholders through a release.',
    email: 'Connectphanikumar@gmail.com',
    phone: '+91 81245 70751',
    githubUrl: 'https://github.com/Phaniramaiah',
    linkedinUrl: 'https://www.linkedin.com/in/phani-kumar-909778168',
    photoUrl: '/phani-kumar.jpg',
    location: 'Hyderabad, India',
    company: 'Zazz IT Solutions Pvt Ltd',
    tenure: 'August 2024 — Present',
    educationDegree: 'B.Tech, Mechanical Engineering',
    educationSchool: 'SRM University, Chennai',
    educationYear: '2019',
    strengths: [
      'End-to-end CI/CD on Jenkins and AWS CodePipeline',
      'Infrastructure as code with reusable Terraform modules',
      'Configuration automation with Ansible playbooks and ad-hoc commands',
      'Docker Compose and Kubernetes for microservice architectures',
      'Monitoring and log analysis with CloudWatch, Splunk, and Datadog',
      'Troubleshooting production and non-production environments',
      'Stakeholder coordination, requirement gathering, and production support',
    ],
  },
  settings: {
    theme: 'ember',
    motion: 'full',
  },
  stats: [
    {
      id: 'stat-years-it',
      value: '5+',
      label: 'Years in IT',
      detail: 'Build, release, and cloud operations',
      order: 1,
    },
    {
      id: 'stat-years-aws',
      value: '4+',
      label: 'Years on AWS',
      detail: 'Setting up, debugging, and troubleshooting AWS',
      order: 2,
    },
    {
      id: 'stat-services',
      value: '19',
      label: 'Services in production',
      detail: 'The AWS and DevOps environment at Zazz',
      order: 3,
    },
    {
      id: 'stat-certifications',
      value: '3',
      label: 'Certifications earned',
      detail: 'AWS Solutions Architect, Cloud Practitioner, and Terraform',
      order: 4,
    },
  ],
  certifications: [
    {
      id: 'cert-aws-saa',
      name: 'AWS Certified Solutions Architect – Associate',
      issuer: 'Amazon Web Services',
      issued: '2024-07',
      expires: '2027-07',
      credentialUrl: 'https://www.credly.com/badges/0dd5c26f-7bae-4600-8100-9157bb634171',
      order: 1,
    },
    {
      id: 'cert-terraform-associate',
      name: 'HashiCorp Certified: Terraform Associate (003)',
      issuer: 'HashiCorp',
      issued: '2024-05',
      expires: '2026-05',
      credentialUrl: 'https://www.credly.com/badges/9ab1a67f-1e31-4222-a76f-4ba9a6ed1337',
      order: 2,
    },
    {
      id: 'cert-aws-ccp',
      name: 'AWS Certified Cloud Practitioner',
      issuer: 'Amazon Web Services',
      issued: '2024-02',
      expires: '2027-02',
      credentialUrl: 'https://www.credly.com/badges/a8a939be-5206-421f-a7ad-d37c1b365060',
      order: 3,
    },
  ],
  achievements: [
    {
      id: 'achievement-platform',
      title: 'High-availability AWS platform for a global client',
      impact:
        'Designed and implemented scalable, secure infrastructure on EC2, ECS, EKS, and VPC so containerized microservices stay available under load.',
      icon: 'cloud',
      tools: ['EC2', 'ECS', 'EKS', 'VPC', 'Route 53'],
      order: 1,
    },
    {
      id: 'achievement-cicd',
      title: 'Releases automated from commit to production',
      impact:
        'Built CI/CD on CodePipeline, CodeBuild, and CodeDeploy with Bitbucket and SonarQube, so tests, quality gates, and deployment run without manual steps.',
      icon: 'pipeline',
      tools: ['CodePipeline', 'CodeBuild', 'CodeDeploy', 'Bitbucket', 'SonarQube'],
      order: 2,
    },
    {
      id: 'achievement-containers',
      title: 'Microservices containerized and scaled',
      impact:
        'Packaged applications with Docker, stored images in ECR, and ran them on ECS with load balancing and scaling for better performance and portability.',
      icon: 'container',
      tools: ['Docker', 'ECR', 'ECS', 'ELB', 'Auto Scaling'],
      order: 3,
    },
    {
      id: 'achievement-security',
      title: 'Least-privilege access and automated TLS',
      impact:
        'Configured IAM roles, Secrets Manager, and ACM to keep credentials out of code, enforce least privilege, and automate SSL/TLS certificate management.',
      icon: 'shield',
      tools: ['IAM', 'Secrets Manager', 'ACM'],
      order: 4,
    },
    {
      id: 'achievement-observability',
      title: 'Monitoring and storage tuned for cost',
      impact:
        'Automated CloudWatch monitoring and alerting, and set S3 lifecycle policies to keep performance steady and storage costs under control.',
      icon: 'chart',
      tools: ['CloudWatch', 'S3'],
      order: 5,
    },
    {
      id: 'achievement-frontend',
      title: 'Faster front-end delivery and feedback',
      impact:
        'Rolled out AWS Amplify for rapid front-end deployments and used Bitbucket Pipelines to shorten feedback loops for developers.',
      icon: 'layers',
      tools: ['Amplify', 'Bitbucket Pipelines'],
      order: 6,
    },
  ],
  skillGroups: [
    {
      id: 'skill-aws',
      title: 'AWS Cloud',
      blurb: 'Compute, networking, storage, and data services.',
      icon: 'cloud',
      order: 1,
      skills: [
        'EC2',
        'VPC',
        'EBS',
        'S3',
        'ELB',
        'Auto Scaling',
        'Route 53',
        'Amplify',
        'Lambda',
        'RDS',
        'DynamoDB',
        'CloudFront',
      ],
    },
    {
      id: 'skill-containers',
      title: 'Containers & orchestration',
      blurb: 'Images, registries, and clusters for microservices.',
      icon: 'container',
      order: 2,
      skills: ['Docker', 'Docker Compose', 'Kubernetes', 'Amazon EKS', 'Amazon ECS', 'Amazon ECR'],
    },
    {
      id: 'skill-cicd',
      title: 'CI/CD',
      blurb: 'Automated build, test, and deployment.',
      icon: 'pipeline',
      order: 3,
      skills: ['Jenkins', 'AWS CodePipeline', 'AWS CodeBuild', 'AWS CodeDeploy', 'Bitbucket Pipelines'],
    },
    {
      id: 'skill-iac',
      title: 'Automation & IaC',
      blurb: 'Repeatable infrastructure and configuration.',
      icon: 'layers',
      order: 4,
      skills: ['Terraform', 'Ansible', 'Shell Scripting', 'Python'],
    },
    {
      id: 'skill-observability',
      title: 'Monitoring & observability',
      blurb: 'Metrics, logs, audit trails, and alerts.',
      icon: 'chart',
      order: 5,
      skills: ['CloudWatch', 'CloudTrail', 'Splunk', 'Datadog'],
    },
    {
      id: 'skill-security',
      title: 'Security & access',
      blurb: 'Least privilege, secrets, and certificates.',
      icon: 'shield',
      order: 6,
      skills: ['IAM', 'Secrets Manager', 'ACM', 'Security Groups'],
    },
    {
      id: 'skill-build',
      title: 'Source, build & quality',
      blurb: 'Version control, artifacts, and code quality.',
      icon: 'code',
      order: 7,
      skills: ['Git', 'GitHub', 'Bitbucket', 'Maven', 'npm', 'Nexus', 'SonarQube'],
    },
    {
      id: 'skill-servers',
      title: 'Servers & operating systems',
      blurb: 'Application servers, web edge, and OS.',
      icon: 'server',
      order: 8,
      skills: ['Linux', 'Windows', 'Apache Tomcat', 'WildFly (JBoss)', 'Nginx', 'Apache'],
    },
    {
      id: 'skill-platforms',
      title: 'Other clouds & tooling',
      blurb: 'Additional platforms and team workflow.',
      icon: 'cloud',
      order: 9,
      skills: ['Azure', 'DigitalOcean', 'Heroku', 'Jira'],
    },
  ],
  experience: [
    {
      id: 'experience-zazz',
      company: 'Zazz IT Solutions Pvt Ltd',
      role: 'AWS DevOps Engineer',
      location: 'Hyderabad',
      start: 'August 2024',
      end: 'Present',
      current: true,
      summary:
        'I design and operate the cloud foundation, container platform, and delivery pipelines for a global client’s high-availability web applications.',
      highlights: [
        'Designed scalable, secure AWS infrastructure on EC2, ECS, EKS, and VPC',
        'Built CI/CD with CodePipeline, CodeBuild, CodeDeploy, Bitbucket, and SonarQube',
        'Containerized services with Docker and ECR, deployed on ECS with load balancing and scaling',
        'Secured access and TLS with IAM roles, Secrets Manager, and ACM',
        'Automated CloudWatch alerting and S3 lifecycle policies for performance and cost',
        'Delivered front ends on Amplify, with Bitbucket Pipelines for faster feedback',
        'Managed Nginx and Apache in front of the applications, with Route 53 DNS',
        'Worked with engineering teams to improve and automate deployment and release',
      ],
      order: 1,
    },
  ],
  projects: [
    {
      id: 'project-global-platform',
      title: 'High-availability platform on AWS',
      client: 'Global client',
      role: 'DevOps Engineer',
      summary:
        'Cloud infrastructure on AWS for scalable, high-availability web applications. A full AWS toolchain and Docker-based microservices, with CI/CD that keeps delivery secure and repeatable.',
      environment: [
        'Docker',
        'Bitbucket',
        'SonarQube',
        'Nginx',
        'Apache',
        'EC2',
        'ECS',
        'ECR',
        'EKS',
        'CodePipeline',
        'CodeBuild',
        'CodeDeploy',
        'Secrets Manager',
        'IAM',
        'ACM',
        'Amplify',
        'VPC',
        'S3',
        'Route 53',
      ],
      responsibilities: [
        'Designed and implemented a scalable, secure AWS footprint with EC2, ECS, EKS, and VPC so containerized microservices stay highly available.',
        'Built CI/CD with CodePipeline, CodeBuild, and CodeDeploy, integrating Bitbucket and SonarQube to automate testing, deployment, and code quality.',
        'Containerized applications with Docker, stored images in ECR, and deployed them on ECS with load balancing and scaling.',
        'Configured IAM roles, Secrets Manager, and ACM for least-privilege access and automated SSL/TLS certificates.',
        'Automated monitoring with CloudWatch and stored data in S3, with alerts and lifecycle policies for performance and cost.',
        'Shipped front ends with AWS Amplify and used Bitbucket Pipelines to shorten feedback inside the delivery workflow.',
      ],
      pipeline: [
        { id: 'source', label: 'Source', detail: 'Bitbucket' },
        { id: 'build', label: 'Build', detail: 'CodeBuild' },
        { id: 'quality', label: 'Quality', detail: 'SonarQube' },
        { id: 'image', label: 'Image', detail: 'Amazon ECR' },
        { id: 'deploy', label: 'Deploy', detail: 'CodeDeploy · ECS & EKS' },
        { id: 'observe', label: 'Observe', detail: 'CloudWatch' },
      ],
      order: 1,
    },
  ],
} satisfies PortfolioContent;

export const sectionIds = [
  'about',
  'skills',
  'certifications',
  'achievements',
  'experience',
  'work',
  'contact',
] as const;

export type SectionId = (typeof sectionIds)[number];
