import type { PortfolioContent } from './types';

export const portfolioContent = {
  profile: {
    name: 'Phani Kumar S',
    role: 'AWS DevOps Engineer',
    eyebrow: 'AWS DevOps Engineer · 5+ years in IT',
    statement:
      'I build secure, high-availability AWS infrastructure and automated release pipelines, so teams can ship to production with confidence.',
    summary:
      'I am an AWS DevOps Engineer at Zazz IT Solutions in Hyderabad, with more than five years in IT and over four years working hands-on with AWS. Since August 2024 I have designed and run cloud infrastructure for production platforms: networks, compute, containers, and the path from source control to production.\n\nSkills Ontario runs as a monolith on Amazon ECS and releases from GitHub with GitHub Actions. Seattle Aquarium and From The Crease run as microservices on Amazon EKS. Seattle Aquarium releases from Bitbucket through CodePipeline, and From The Crease releases through CodePipeline. Wildlife Health runs on EC2 with Auto Scaling and releases with Jenkins. Happy Teacher is a RAG chatbot on EC2, using Pinecone, MongoDB, Postgres, ChatGPT mini, and S3. Terraform defines the environments, and CloudWatch covers alerts and rollback. I also own certificates and secrets, CloudWatch monitoring, S3 lifecycle policies, Amplify front-end delivery, and the Nginx and Apache edges in front of the applications.\n\nBeyond the Zazz stack I work with Jenkins, Terraform, Ansible, Kubernetes, Maven, Nexus, Splunk, and Datadog, across Linux and Windows. I am comfortable troubleshooting production and non-production issues, and coordinating with engineering teams and stakeholders through a release.',
    email: 'Connectphanikumar@gmail.com',
    phone: '+91 81245 70751',
    githubUrl: 'https://github.com/Phaniramaiah',
    linkedinUrl: 'https://www.linkedin.com/in/phani-kumar-909778168',
    photoUrl: '/phani-kumar.jpg',
    location: 'Hyderabad, India',
    company: 'Zazz IT Solutions Pvt Ltd',
    tenure: 'August 2024 — Present',
    educationDegree: 'B.Tech, Mechanical Engineering',
    educationSchool: 'SRM University, Chennai',
    educationYear: '2019',
    strengths: [
      'End-to-end CI/CD on Jenkins and AWS CodePipeline',
      'Infrastructure as code with reusable Terraform modules',
      'Configuration automation with Ansible playbooks and ad-hoc commands',
      'Docker Compose and Kubernetes for microservice architectures',
      'Monitoring and log analysis with CloudWatch, Splunk, and Datadog',
      'Troubleshooting production and non-production environments',
      'Stakeholder coordination, requirement gathering, and production support',
    ],
  },
  settings: {
    theme: 'ember',
    motion: 'full',
  },
  stats: [
    {
      id: 'stat-years-it',
      value: '5+',
      label: 'Years in IT',
      detail: 'Build, release, and cloud operations',
      order: 1,
    },
    {
      id: 'stat-years-aws',
      value: '4+',
      label: 'Years on AWS',
      detail: 'Setting up, debugging, and troubleshooting AWS',
      order: 2,
    },
    {
      id: 'stat-services',
      value: '19',
      label: 'Services in production',
      detail: 'The AWS and DevOps environment at Zazz',
      order: 3,
    },
    {
      id: 'stat-certifications',
      value: '3',
      label: 'Certifications earned',
      detail: 'AWS Solutions Architect, Cloud Practitioner, and Terraform',
      order: 4,
    },
  ],
  certifications: [
    {
      id: 'cert-aws-saa',
      name: 'AWS Certified Solutions Architect – Associate',
      issuer: 'Amazon Web Services',
      issued: '2024-07',
      expires: '2027-07',
      credentialUrl: 'https://www.credly.com/badges/0dd5c26f-7bae-4600-8100-9157bb634171',
      order: 1,
    },
    {
      id: 'cert-terraform-associate',
      name: 'HashiCorp Certified: Terraform Associate (003)',
      issuer: 'HashiCorp',
      issued: '2024-05',
      expires: '2026-05',
      credentialUrl: 'https://www.credly.com/badges/9ab1a67f-1e31-4222-a76f-4ba9a6ed1337',
      order: 2,
    },
    {
      id: 'cert-aws-ccp',
      name: 'AWS Certified Cloud Practitioner',
      issuer: 'Amazon Web Services',
      issued: '2024-02',
      expires: '2027-02',
      credentialUrl: 'https://www.credly.com/badges/a8a939be-5206-421f-a7ad-d37c1b365060',
      order: 3,
    },
  ],
  achievements: [
    {
      id: 'achievement-platform',
      title: 'Production platforms on AWS',
      impact:
        'Designed and implemented scalable, secure infrastructure: Skills Ontario as a monolith on ECS, Seattle Aquarium and From The Crease as microservices on EKS, Wildlife Health on EC2 Auto Scaling, and Happy Teacher, a RAG chatbot, on EC2.',
      icon: 'cloud',
      tools: ['EC2', 'ECS', 'EKS', 'Auto Scaling', 'VPC'],
      order: 1,
    },
    {
      id: 'achievement-cicd',
      title: 'Releases automated from commit to production',
      impact:
        'Automated releases three ways: GitHub Actions for Skills Ontario, CodePipeline from Bitbucket for Seattle Aquarium, and Jenkins for Wildlife Health.',
      icon: 'pipeline',
      tools: ['GitHub Actions', 'CodePipeline', 'Jenkins', 'Terraform'],
      order: 2,
    },
    {
      id: 'achievement-containers',
      title: 'Microservices containerized and scaled',
      impact:
        'Packaged applications with Docker, stored images in ECR, and ran them on ECS with load balancing and scaling for better performance and portability.',
      icon: 'container',
      tools: ['Docker', 'ECR', 'ECS', 'ELB', 'Auto Scaling'],
      order: 3,
    },
    {
      id: 'achievement-security',
      title: 'Least-privilege access and automated TLS',
      impact:
        'Configured IAM roles, Secrets Manager, and ACM to keep credentials out of code, enforce least privilege, and automate SSL/TLS certificate management.',
      icon: 'shield',
      tools: ['IAM', 'Secrets Manager', 'ACM'],
      order: 4,
    },
    {
      id: 'achievement-observability',
      title: 'Monitoring and storage tuned for cost',
      impact:
        'Automated CloudWatch monitoring and alerting, and set S3 lifecycle policies to keep performance steady and storage costs under control.',
      icon: 'chart',
      tools: ['CloudWatch', 'S3'],
      order: 5,
    },
    {
      id: 'achievement-frontend',
      title: 'Faster front-end delivery and feedback',
      impact:
        'Rolled out AWS Amplify for rapid front-end deployments and used Bitbucket Pipelines to shorten feedback loops for developers.',
      icon: 'layers',
      tools: ['Amplify', 'Bitbucket Pipelines'],
      order: 6,
    },
  ],
  skillGroups: [
    {
      id: 'skill-aws',
      title: 'AWS Cloud',
      blurb: 'Compute, networking, storage, and data services.',
      icon: 'cloud',
      order: 1,
      skills: [
        'EC2',
        'VPC',
        'EBS',
        'S3',
        'ELB',
        'Auto Scaling',
        'Route 53',
        'Amplify',
        'Lambda',
        'RDS',
        'DynamoDB',
        'CloudFront',
      ],
    },
    {
      id: 'skill-containers',
      title: 'Containers & orchestration',
      blurb: 'Images, registries, and clusters for microservices.',
      icon: 'container',
      order: 2,
      skills: ['Docker', 'Docker Compose', 'Kubernetes', 'Amazon EKS', 'Amazon ECS', 'Amazon ECR'],
    },
    {
      id: 'skill-cicd',
      title: 'CI/CD',
      blurb: 'Automated build, test, and deployment.',
      icon: 'pipeline',
      order: 3,
      skills: ['Jenkins', 'AWS CodePipeline', 'AWS CodeBuild', 'AWS CodeDeploy', 'Bitbucket Pipelines'],
    },
    {
      id: 'skill-iac',
      title: 'Automation & IaC',
      blurb: 'Repeatable infrastructure and configuration.',
      icon: 'layers',
      order: 4,
      skills: ['Terraform', 'Ansible', 'Shell Scripting', 'Python'],
    },
    {
      id: 'skill-observability',
      title: 'Monitoring & observability',
      blurb: 'Metrics, logs, audit trails, and alerts.',
      icon: 'chart',
      order: 5,
      skills: ['CloudWatch', 'CloudTrail', 'Splunk', 'Datadog'],
    },
    {
      id: 'skill-security',
      title: 'Security & access',
      blurb: 'Least privilege, secrets, and certificates.',
      icon: 'shield',
      order: 6,
      skills: ['IAM', 'Secrets Manager', 'ACM', 'Security Groups'],
    },
    {
      id: 'skill-build',
      title: 'Source, build & quality',
      blurb: 'Version control, artifacts, and code quality.',
      icon: 'code',
      order: 7,
      skills: ['Git', 'GitHub', 'Bitbucket', 'Maven', 'npm', 'Nexus', 'SonarQube'],
    },
    {
      id: 'skill-servers',
      title: 'Servers & operating systems',
      blurb: 'Application servers, web edge, and OS.',
      icon: 'server',
      order: 8,
      skills: ['Linux', 'Windows', 'Apache Tomcat', 'WildFly (JBoss)', 'Nginx', 'Apache'],
    },
    {
      id: 'skill-platforms',
      title: 'Other clouds & tooling',
      blurb: 'Additional platforms and team workflow.',
      icon: 'cloud',
      order: 9,
      skills: ['Azure', 'DigitalOcean', 'Heroku', 'Jira'],
    },
    {
      id: 'skill-ai',
      title: 'AI & retrieval',
      blurb: 'Grounded answers for the Happy Teacher chatbot.',
      icon: 'layers',
      order: 10,
      skills: ['RAG', 'Pinecone', 'MongoDB', 'PostgreSQL', 'ChatGPT mini', 'Amazon S3'],
    },
  ],
  experience: [
    {
      id: 'experience-zazz',
      company: 'Zazz IT Solutions Pvt Ltd',
      role: 'AWS DevOps Engineer',
      location: 'Hyderabad',
      start: 'August 2024',
      end: 'Present',
      current: true,
      summary:
        'I design and operate the cloud foundation and delivery pipelines for Skills Ontario, Seattle Aquarium, From The Crease, Wildlife Health, and Happy Teacher.',
      highlights: [
        'Ran Skills Ontario as a monolith on ECS, Seattle Aquarium and From The Crease as microservices on EKS, and Wildlife Health on EC2 Auto Scaling',
        'Released Skills Ontario from GitHub with GitHub Actions, Seattle Aquarium from Bitbucket through CodePipeline, From The Crease through CodePipeline, and Wildlife Health with Jenkins',
        'Deployed Happy Teacher, a RAG chatbot, on EC2 with Pinecone, MongoDB, Postgres, ChatGPT mini, and S3',
        'Defined each environment in Terraform, and watched releases in CloudWatch so a failed deploy can roll back',
        'Secured access and TLS with IAM roles, Secrets Manager, and ACM',
        'Automated CloudWatch alerting and S3 lifecycle policies for performance and cost',
        'Delivered front ends on Amplify when a client needed a shorter feedback loop',
        'Managed Nginx and Apache in front of the applications, with Route 53 DNS',
        'Worked with engineering teams to improve and automate deployment and release',
      ],
      order: 1,
    },
  ],
  projects: [
    {
      id: 'project-skills-ontario',
      title: 'Monolith on Amazon ECS',
      client: 'Skills Ontario',
      role: 'DevOps Engineer',
      summary:
        'A skills and trades platform that connects youth to technical careers. I run it as one application on Amazon ECS. GitHub Actions builds, tests, and deploys from GitHub, and the service scales out for national-event traffic.',
      engine: 'GitHub Actions',
      environment: [
        'GitHub',
        'GitHub Actions',
        'Amazon ECS',
        'Terraform',
        'Docker',
        'ECR',
        'VPC',
        'ELB',
        'Auto Scaling',
        'IAM',
        'Secrets Manager',
        'ACM',
        'CloudWatch',
      ],
      responsibilities: [
        'Defined the VPC, load balancer, and ECS service in Terraform so the monolith can be reproduced for event load.',
        'Ran builds, tests, and deploys in GitHub Actions from GitHub, then pushed the image to ECR.',
        'Released onto the ECS service from the same workflow, and rolled back from CloudWatch when a release failed.',
        'Scaled the ECS service horizontally for high-traffic events, and kept credentials and TLS in Secrets Manager and ACM.',
      ],
      pipeline: [
        { id: 'source', label: 'Source', detail: 'GitHub' },
        { id: 'build', label: 'Build', detail: 'GitHub Actions' },
        { id: 'test', label: 'Test', detail: 'GitHub Actions' },
        { id: 'provision', label: 'Provision', detail: 'Terraform' },
        { id: 'image', label: 'Image', detail: 'Amazon ECR' },
        { id: 'deploy', label: 'Deploy', detail: 'GitHub Actions · ECS' },
        { id: 'observe', label: 'Observe', detail: 'CloudWatch · rollback' },
      ],
      order: 1,
    },
    {
      id: 'project-seattle-aquarium',
      title: 'Microservices on Amazon EKS',
      client: 'Seattle Aquarium',
      role: 'DevOps Engineer',
      summary:
        'Digital kiosks, ticketing, and mobile experiences for the aquarium. I run the stack as microservices on Amazon EKS. Bitbucket feeds CodePipeline, Terraform sizes the node groups for foot traffic, and each service ships blue/green.',
      engine: 'AWS CodePipeline',
      environment: [
        'Bitbucket',
        'Amazon EKS',
        'Kubernetes',
        'Terraform',
        'Docker',
        'ECR',
        'VPC',
        'ELB',
        'CodePipeline',
        'CodeBuild',
        'CodeDeploy',
        'SonarQube',
        'IAM',
        'Secrets Manager',
        'ACM',
        'CloudWatch',
      ],
      responsibilities: [
        'Defined the EKS cluster and node groups in Terraform, sized for exhibit foot traffic, so kiosk, ticketing, and content services scale on their own.',
        'Built each service in CodeBuild from Bitbucket, gated the release on SonarQube, and stored the image in ECR.',
        'Cut over with CodeDeploy blue/green onto EKS so a bad release never stays in front of visitors.',
        'Kept short-lived access in IAM, secrets in Secrets Manager, certificates in ACM, and uptime alerts in CloudWatch.',
      ],
      pipeline: [
        { id: 'source', label: 'Source', detail: 'Bitbucket' },
        { id: 'build', label: 'Build', detail: 'CodeBuild' },
        { id: 'quality', label: 'Quality', detail: 'SonarQube' },
        { id: 'provision', label: 'Provision', detail: 'Terraform' },
        { id: 'image', label: 'Image', detail: 'Amazon ECR' },
        { id: 'deploy', label: 'Deploy', detail: 'CodeDeploy · EKS blue/green' },
        { id: 'observe', label: 'Observe', detail: 'CloudWatch' },
      ],
      order: 2,
    },
    {
      id: 'project-wildlife-health',
      title: 'EC2 with Auto Scaling',
      client: 'Wildlife Health',
      role: 'DevOps Engineer',
      summary:
        'Field reporting, lab workflows, and national data sharing for wildlife health surveillance. I run it on EC2 with Auto Scaling. Jenkins builds and deploys onto the group, Terraform defines it, and CloudWatch watches instance health.',
      engine: 'Jenkins',
      environment: [
        'Jenkins',
        'EC2',
        'Auto Scaling',
        'Terraform',
        'ELB',
        'VPC',
        'Nginx',
        'IAM',
        'Secrets Manager',
        'ACM',
        'CloudWatch',
        'Route 53',
      ],
      responsibilities: [
        'Defined the VPC, load balancer, and Auto Scaling group in Terraform, sized for migration-season and incident load.',
        'Built and tested each commit in Jenkins, then deployed onto the Auto Scaling group from the same job.',
        'Kept Nginx and Route 53 in front of the instances, with a rollback path when a Jenkins deploy failed.',
        'Watched instance health and scaling events in CloudWatch, and kept credentials and TLS in Secrets Manager and ACM.',
      ],
      pipeline: [
        { id: 'source', label: 'Source', detail: 'Git' },
        { id: 'build', label: 'Build', detail: 'Jenkins' },
        { id: 'test', label: 'Test', detail: 'Jenkins' },
        { id: 'provision', label: 'Provision', detail: 'Terraform' },
        { id: 'deploy', label: 'Deploy', detail: 'Jenkins · EC2 Auto Scaling' },
        { id: 'edge', label: 'Edge', detail: 'Nginx · Route 53' },
        { id: 'observe', label: 'Observe', detail: 'CloudWatch · rollback' },
      ],
      order: 3,
    },
    {
      id: 'project-from-the-crease',
      title: 'Microservices on Amazon EKS',
      client: 'From The Crease',
      role: 'DevOps Engineer',
      summary:
        'A hockey goalie coaching product across web, iOS, and Android: programs, onboarding, and performance tracking in one place. I run the backend as microservices on Amazon EKS and release them with CodePipeline.',
      engine: 'AWS CodePipeline',
      environment: [
        'Amazon EKS',
        'Kubernetes',
        'CodePipeline',
        'CodeBuild',
        'CodeDeploy',
        'Docker',
        'ECR',
        'Terraform',
        'VPC',
        'ELB',
        'SonarQube',
        'IAM',
        'CloudWatch',
      ],
      responsibilities: [
        'Designed the EKS cluster and node groups so coaching, media, and account services deploy and scale on their own.',
        'Built each service in CodeBuild, gated the release on SonarQube, and stored the image in ECR.',
        'Released the microservices with CodePipeline and CodeDeploy onto EKS.',
        'Defined the cluster in Terraform and watched the rollout in CloudWatch.',
      ],
      pipeline: [
        { id: 'source', label: 'Source', detail: 'Git' },
        { id: 'build', label: 'Build', detail: 'CodeBuild' },
        { id: 'quality', label: 'Quality', detail: 'SonarQube' },
        { id: 'provision', label: 'Provision', detail: 'Terraform' },
        { id: 'image', label: 'Image', detail: 'Amazon ECR' },
        { id: 'deploy', label: 'Deploy', detail: 'CodePipeline · EKS' },
        { id: 'observe', label: 'Observe', detail: 'CloudWatch' },
      ],
      order: 4,
    },
    {
      id: 'project-happy-teacher',
      title: 'RAG chatbot on EC2',
      client: 'Happy Teacher',
      role: 'DevOps Engineer',
      summary:
        'Your AI buddy for personalized support. Happy Teacher is a private well-being app for people who work with young children. I host the Happi chatbot on EC2 and ground its answers with retrieval.',
      engine: 'RAG on EC2',
      environment: [
        'RAG',
        'Pinecone',
        'MongoDB',
        'PostgreSQL',
        'ChatGPT mini',
        'Amazon S3',
        'EC2',
        'IAM',
        'CloudWatch',
      ],
      responsibilities: [
        'Deployed the Happi chatbot on EC2 so educators can ask for personalized support from the app.',
        'Grounded replies with RAG: relevant context is retrieved from Pinecone, with records kept in MongoDB and Postgres.',
        'Stored documents and media in S3, and called ChatGPT mini to write the answer from that context.',
        'Kept IAM around the host and watched the instance in CloudWatch.',
      ],
      pipeline: [
        { id: 'retrieve', label: 'Retrieve', detail: 'Pinecone' },
        { id: 'records', label: 'Records', detail: 'MongoDB · Postgres' },
        { id: 'generate', label: 'Generate', detail: 'ChatGPT mini' },
        { id: 'files', label: 'Files', detail: 'Amazon S3' },
        { id: 'deploy', label: 'Deploy', detail: 'Amazon EC2' },
        { id: 'observe', label: 'Observe', detail: 'CloudWatch' },
      ],
      order: 5,
    },
  ],
} satisfies PortfolioContent;

export const sectionIds = [
  'about',
  'skills',
  'certifications',
  'achievements',
  'experience',
  'work',
  'contact',
] as const;

export type SectionId = (typeof sectionIds)[number];
